<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search cis_user
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["cis_user/new", "Create cis_user"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "cis_user/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUname" class="col-sm-2 control-label">Uname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uname", "size" => 30, "class" => "form-control", "id" => "fieldUname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPasswd" class="col-sm-2 control-label">Passwd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["passwd", "size" => 30, "class" => "form-control", "id" => "fieldPasswd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOpenid" class="col-sm-2 control-label">Openid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["openid", "size" => 30, "class" => "form-control", "id" => "fieldOpenid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFrom" class="col-sm-2 control-label">From</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["from", "size" => 30, "class" => "form-control", "id" => "fieldFrom"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
